[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gutenberg_registry = "NRrK71RxAHpt5CdLUWgRzTuzMopnRBnEqCiCku6J517"

[programs.devnet]
gutenberg_registry = "NRrK71RxAHpt5CdLUWgRzTuzMopnRBnEqCiCku6J517"

[programs.mainnet]
gutenberg_registry = "NRrK71RxAHpt5CdLUWgRzTuzMopnRBnEqCiCku6J517"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

