[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gutenberg_registry = "gut2vkAAtjGsxj3VDkFcRCB1HbwTd6VN2u6wZMno6Wt"

[programs.devnet]
gutenberg_registry = "gut2vkAAtjGsxj3VDkFcRCB1HbwTd6VN2u6wZMno6Wt"

[programs.mainnet]
gutenberg_registry = "gut2vkAAtjGsxj3VDkFcRCB1HbwTd6VN2u6wZMno6Wt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

