[package]
name = "gutenberg_registry"
version = "0.1.0"
description = "Gutenberg release registry"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "gutenberg_registry"

[features]
anchor-debug = []
custom-heap = []
custom-panic = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
solana-sha256-hasher = "2.3.0"
