export const STORAGE_ENDPOINT_KEY = Symbol('STORAGE_ENDPOINT_KEY');
export const STORAGE_BUCKET_KEY = Symbol('STORAGE_BUCKET_KEY');
export const STORAGE_ACCESS_KEY_KEY = Symbol('STORAGE_ACCESS_KEY_KEY');
export const STORAGE_SECRET_KEY_KEY = Symbol('STORAGE_SECRET_KEY_KEY');
export const SOLANA_RPC_URL_KEY = Symbol('SOLANA_RPC_URL_KEY');
export const SOLANA_PRIVATE_KEY_KEY = Symbol('SOLANA_PRIVATE_KEY_KEY');
export const REGISTRY_PROGRAM_ID_KEY = Symbol('REGISTRY_PROGRAM_ID_KEY');
